openapi: 3.0.3
info:
  title: Verwaltungscloud Antragsportal
  description: |-
    Das Verwaltungscloud Antragsportal ermöglicht das Stellen von Onlineanträgen für integrierte Fachverfahren.
    
  contact:
    email: info@verwaltungscloud.sh
  version: 0.0.1

servers:
  - url: https://api.antrag.dev.verwaltungs.cloud/v1
tags:
  - name: health
    description: Healthchecks
    
  - name: receivers
    description: application receiving entities
    
paths:
  # healthchecks
  /health:
    get: 
      tags:
        - health
      summary: Healthcheck on the Backend Service
      operationId: getHealth
      responses:
        200:
          $ref: '#/components/responses/HealthcheckOK'
          
  /health/mongodbconnection:
    get: 
      tags:
        - health
      summary: Healthcheck on the MongoDB Connection
      description: checks if the backend service is connected to the MongoDB
      operationId: getHealthMongoDB
      responses:
        200:
          $ref: '#/components/responses/HealthcheckOK'
  
  /health/gotenberg:
    get: 
      tags:
        - health
      summary: Healthcheck on the Gotenberg Service
      description: check if the Gotenberg service (PDF rendering engine) is up and reachable
      operationId: getHealthGotenberg
      responses:
        200:
          $ref: '#/components/responses/HealthcheckOK'
          

  # receivers
  /receivers:
    get: 
      tags: 
        - receivers
      summary: query receivers (odatafy enabled)
      description: Queries receivers.<br>Route is odatafy compatible. <br>Documentation and examples can be found <a href=http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_QueryOptions>here</a>.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ReceiverPublic'
                  count: 
                    $ref: '#/components/schemas/OdatafyCount'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalServerError'
          
              

components:

  responses: 
  
    HealthcheckOK:
      description: Healthcheck successful
      content: 
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                default: OK
      
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              msg: 
                type: string
                example: 'malformed filter expression'
                description: error message
      
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              msg: 
                type: string
                example: 'Internal Server Error'
                description: error message
    
    
      

  
  schemas:
    OdatafyCount: 
      type: number
      description: number of total query results, regardless of the returned number of documents (useful for pagination)
  
    ReceiverPublic:
      type: object
      properties:
        _id:
          type: string
          format: Mongo ObjectId
          example: 507f1f77bcf86cd799439011
        name: 
          type: string
          example: Amt Hüttener Berge
        alias:
          type: string
          description: nickname of the receiver to match it with tenants in the target system
          format: 'lowercase no spaces'
          example: amthb
        logoUrl: 
          type: string
          description: URL for the receivers logo to be displayed
          example: https://minio-api.tools.verwaltungscloud.dev/verwaltungscloud-public-assets/LogoDL%20zoom.png
          
    #Receiver:
    #  allOf: 
    #      - $ref: '#/components/schemas/ReceiverPublic'
    #      - type: object
    #        properties: 
    #          submissionTargetApiBaseUrl: 
    #            type: string
    #            description: Base URL of the API in the target system to# send the final submission t#o
    #            example: https://api.rd-eck.verwaltungscloud.sh/v1
    
    
    TransactionMetaSchema: 
      type: object
      properties: 
        name: 
          type: string
          example: 'Antrag auf Ermäßigung der Kita-Beiträge (Kurzversion)'
        alias: 
          type: string
          example: 'sozstafkitashort'
        stepCount:
          type: number
          description: '(max.) number of steps in the transaction'
        iconUrl: 
          type: string 
          description: URL for the transaction icon to be displayed
          example: https://minio-api.tools.verwaltungscloud.dev/verwaltungscloud-public-assets/LogoDL%20zoom.png